# BUILDING FOR CI CD - LARAVEL with Vue
name: EVENPAR - ProjectSigma_Projects-API Build and Push to CI-Pipeline Branch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  APPLICATION_NAME: "ProjectSigma_Projects-API"
  GIT_USERNAME: "engtech-projects"
  REPOSITORY_NAME: "ProjectSigma_Projects-API"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "EVENPAR - build ProjectSigma_Projects-API"
  cancel-in-progress: true

jobs:
  build-evenpar:
    runs-on: ubuntu-latest
    env:
      APP_ENV: 'local'
      DB_CONNECTION: 'mysql'
      DB_HOST: '172.23.133.21'
      DB_PORT: '3306'
      DB_DATABASE: 'projectsigma_projects'
      DB_USERNAME: 'engtech'
      DB_PASSWORD: 'tVhjgWzsklpW'
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_mysql
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: ZeroTier Evenpar
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Build Laravel
        run: |
              composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
              php artisan key:generate
              php artisan migrate
              php artisan db:seed
              rm -rf .env
              rm -rf .git
              rm -rf .gitignore
              git config --global user.email "engtechsolutions2020@gmail.com"
              git config --global user.name "EngtechDeploy"
              git init
              git add -A
              git commit -m 'deploy to CI-Pipeline'
              git push -f https://$GIT_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GIT_USERNAME/$REPOSITORY_NAME.git master:ci-pipe-evenpar
        shell: bash
